name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Install deps
      run: sudo apt-get install -y libpango1.0-dev libgraphene-1.0-dev libgtk-4-dev
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
